name: Publish to Cargo

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags, e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Verify the application compiles
    - name: Build the project
      run: cargo build --release

    # Run tests to ensure stability
    - name: Run tests
      run: cargo test --verbose

    # Publish to Cargo
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish
